import {
  exactMatch,
  jsonDiff,
  levenshteinScorer,
  listContains,
  numericDiff,
} from './deterministic';
import { answerSimilarity, embeddingSimilarity } from './embedding';
import {
  answerCorrectness,
  answerRelevancy,
  contextEntityRecall,
  contextPrecision,
  contextRecall,
  contextRelevancy,
  factuality,
  humor,
  moderation,
  possible,
  sql,
  summary,
  translation,
} from './llm';

export const scorers = {
  answerCorrectness,
  answerRelevancy,
  answerSimilarity,
  contextEntityRecall,
  contextPrecision,
  contextRecall,
  contextRelevancy,
  embeddingSimilarity,
  exactMatch,
  factual: factuality,
  humor,
  jsonDiff,
  levenshtein: levenshteinScorer,
  listContains,
  moderation,
  numericDiff,
  possible,
  sql,
  summary,
  translation,
};
